SPACE cycle pause; script-binding uosc/flash-pause-indicator
RIGHT seek 5; script-binding uosc/flash-timeline
LEFT seek -5; script-binding uosc/flash-timeline
Shift+RIGHT seek 30; script-binding uosc/flash-timeline
Shift+LEFT seek -30; script-binding uosc/flash-timeline
UP no-osd add volume 5; script-binding uosc/flash-volume
DOWN no-osd add volume -5; script-binding uosc/flash-volume
m no-osd cycle mute; script-binding uosc/flash-volume
f cycle fullscreen
TAB script-binding uosc/toggle-ui
MBTN_RIGHT script-binding uosc/menu-blurred
