# PremiumMedia uosc overrides
timeline_style=line
timeline_line_width=4
timeline_size=52
timeline_border=0
timeline_step=5
timeline_cache=no
timeline_heatmap=no
progress=always
progress_size=3
progress_line_width=24
controls=menu,<has_sub>subtitles,<has_many_audio>audio,space,prev,play-pause,next,space,fullscreen
controls_size=46
controls_margin=14
controls_spacing=6
controls_persistency=paused
volume=right
volume_size=50
volume_border=0
volume_step=2
volume_persistency=paused
menu_item_height=50
menu_min_width=320
menu_padding=8
top_bar=no-border
top_bar_size=44
top_bar_controls=right
top_bar_title=yes
top_bar_persistency=paused
window_border_size=1
scale=1.08
scale_fullscreen=1.12
font_scale=1.0
text_border=1.0
border_radius=10
color=foreground=f5f5f5,foreground_text=111111,background=111111,background_text=f5f5f5,window_border=2d2d2d,curtain=050505,success=d7f0d7,error=ff7474,match=ffffff,heatmap=8a8a8a
opacity=timeline=0.96,position=1,chapters=0.55,slider=0.92,slider_gauge=1,controls=0.68,speed=0.78,menu=0.97,submenu=0.5,border=0.7,title=0.96,tooltip=0.96,thumbnail=1,curtain=0.78,idle_indicator=0.75,audio_indicator=0.5,buffering_indicator=0.28,playlist_position=0.75,heatmap=0.2,pause_indicator=0.82
animation_duration=140
flash_duration=900
proximity_in=72
proximity_out=165
font_bold=no
autohide=no
pause_indicator=flash
